# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45e30f770135719caf210dc87740613a6f2ea4da24cfecfb6763b53c2a9d6ed76f923f3e5ef4d0abdcaff0ac0ce6809f7b243a82de54fedb7f7b9d6f29192a75

test:
  secret_key_base: e129f71b697e59881d563da69a1f89e77624a6c57a302118033227fa7d47e1ba487d1172f1488c20af4d12a587ea81b112ff4c82ae7cef16be7c86d523fb5cd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
